import {currentPageState} from "nrstate"
import PageStateProvider from "nrstate-client/PageStateProvider"
import Footer from "@/components/Footer"
import Navbar from "@/components/Navbar"
import { PrefState,initialPrefState,path } from "@/state/submit-prefcode"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        style={{
          height: "100vh"
        }}
      >
        <PageStateProvider
          current={currentPageState<PrefState>(initialPrefState, path)}>
          <Navbar />
          {children}
          <Footer />
        </PageStateProvider>
      </body>
    </html>
  )
}
