import Footer from "@/components/Footer"
import Navbar from "@/components/Navbar"
import type { Metadata } from "next"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        style={{
          height: "100vh"
        }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
